baseURL = "https://artistsarejerks-site.pages.dev/"
languageCode = "en-us"
title = "Artists Are Jerks"

assetDir = "assets"
[pagination]
  pagerSize = 10

[params]
  description = "A playful roast of ego, hype, and half-baked art."

[menu]

  [[menu.main]]
    identifier = "whats-a-jerk"
    name = "What's a Jerk?"
    url = "/whats-a-jerk/"
    weight = 1

  [[menu.main]]
    identifier = "artist-studio-guide"
    name = "Artist Studio Guide"
    url = "/artist-studio-guide/"
    weight = 2

  [[menu.main]]
    identifier = "how-art-works"
    name = "How Art Works"
    url = "/how-art-works/"
    weight = 3

  [[menu.main]]
    identifier = "gatekeepers"
    name = "Gatekeepers"
    url = "/gatekeepers/"
    weight = 4

  [[menu.main]]
    identifier = "class-room"
    name = "Classroom"
    url = "/class-room/"
    weight = 5

  [[menu.main]]
    identifier = "attention-lab"
    name = "Attention Lab"
    url = "/attention-lab/"
    weight = 6

  [[menu.main]]
    identifier = "art-wheel"
    name = "Art History Wheel"
    url = "/art-wheel/"
    weight = 7