baseURL = "https://artistsarejerks-site.pages.dev/"
languageCode = "en-us"
title = "Artists Are Jerks"

assetDir = "assets"
[pagination]
  pagerSize = 10

[params]
  description = "A playful roast of ego, hype, and half-baked art."

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "art-wheel"
    name = "Art Wheel"
    url = "/art-wheel/"
    weight = 2

  [[menu.main]]
    identifier = "lab"
    name = "Lab"
    url = "/lab/"
    weight = 3

    [[menu.main]]
      parent = "lab"
      name = "Aesthetic Break #1"
      url = "/lab/aesthetic-break-01/"
      weight = 1

  [[menu.main]]
    identifier = "art-education"
    name = "Art Education"
    url = "/art-education/"
    weight = 4

  [[menu.main]]
    identifier = "movements"
    name = "Movements"
    url = "/movements/"
    weight = 5

  [[menu.main]]
    identifier = "artists"
    name = "Artists' Work"
    url = "/artists/"
    weight = 6

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 99